---
- name: Deploy metal-metrics-exporter
  k8s:
    definition: "{{ lookup('template', 'metrics-exporters/metal-metrics-exporter.yaml') }}"
    namespace: "{{ monitoring_namespace }}"
    apply: true

- name: Deploy rethinkdb-exporter
  k8s:
    definition: "{{ lookup('template', 'metrics-exporters/rethinkdb-exporter.yaml') }}"
    namespace: "{{ monitoring_namespace }}"
    apply: true

- name: Deploy event-exporter
  k8s:
    definition: "{{ lookup('template', 'metrics-exporters/event-exporter.yaml') }}"
    namespace: "{{ monitoring_namespace }}"
    apply: true

- name: Get kubeconfig for virtual garden access
  virtual_garden_kubeconfig:
    garden_name: "{{ gardener_monitoring_certs_garden_name }}"
  when: monitoring_gardener_enabled

- name: Deploy seed-kubecfg secret
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: seed-kubecfg
        namespace: "{{ monitoring_namespace }}"
      stringData:
        kubecfg.yaml: "{{ virtual_garden_kubeconfig }}"
  when: monitoring_gardener_enabled

- name: Deploy gardener-metrics-exporter
  k8s:
    definition: "{{ lookup('template', 'metrics-exporters/gardener-metrics-exporter.yaml') }}"
    namespace: "{{ monitoring_namespace }}"
    apply: true
  when: monitoring_gardener_enabled
