---
- name: Deploy metal-metrics-exporter
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'metrics-exporters/metal-metrics-exporter.yaml') }}"
    namespace: "{{ monitoring_namespace }}"
    apply: true

- name: Deploy rethinkdb-exporter
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'metrics-exporters/rethinkdb-exporter.yaml') }}"
    namespace: "{{ monitoring_namespace }}"
    apply: true

- name: Deploy event-exporter
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'metrics-exporters/event-exporter.yaml') }}"
    namespace: "{{ monitoring_namespace }}"
    apply: true
  when: event_exporter_enabled | bool

- name: Remove event-exporter
  kubernetes.core.k8s:
    state: absent
    definition:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: event-exporter
          namespace: "{{ monitoring_namespace }}"
      - apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: event-exporter
          namespace: "{{ monitoring_namespace }}"
      - apiVersion: v1
        kind: ConfigMap
        metadata:
          name: event-exporter-cfg
          namespace: "{{ monitoring_namespace }}"
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          name: event-exporter
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: event-exporter
  when: not event_exporter_enabled | bool

- name: Create garden cluster kubeconfig Secret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: virtual-garden-kubeconfig-garden-cluster
        namespace: "{{ monitoring_namespace }}"
      type: Opaque
      stringData:
        GARDEN_CLUSTER_KUBECONFIG: "{{ monitoring_virtual_garden_kubeconfig_refresher_garden_cluster_kubeconfig }}"
  when: monitoring_virtual_garden_kubeconfig_refresher_garden_cluster_enabled

- name: Deploy virtual-garden-kubeconfig-refresher
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'virtual-garden-kubeconfig-refresher.yaml') }}"
    namespace: "{{ monitoring_namespace }}"
    apply: true
  when: monitoring_gardener_enabled

- name: Deploy gardener-metrics-exporter
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'metrics-exporters/gardener-metrics-exporter.yaml') }}"
    namespace: "{{ monitoring_namespace }}"
    apply: true
  when: monitoring_gardener_enabled
