---
metal_deployment_token_secret_name: metal-apiserver-admin-token
metal_deployment_token_secret_namespace: "{{ metal_control_plane_namespace }}"
metal_deployment_token_secret_key: admin_editor_token
