---
argument_specs:
  main:
    short_description: Deploys the prometheus blackbox-exporter in a systemd-managed Docker container
    options:
      monitoring_blackbox_exporter_etc_host_dir:
        type: str
        description: Host directory for the blackbox-exporter configuration.
      monitoring_blackbox_exporter_image_name:
        type: str
        description: Image name of the blackbox-exporter.
      monitoring_blackbox_exporter_image_tag:
        type: str
        description: Image tag of the blackbox-exporter.
      monitoring_blackbox_exporter_port:
        type: int
        description: Port the blackbox-exporter listens on.
      monitoring_blackbox_exporter_docker_log_driver:
        type: str
        description: Docker log driver for the blackbox-exporter container.
