---
- name: Restart caclmgrd
  ansible.builtin.systemd:
    name: caclmgrd
    state: restarted

- name: Config load
  ansible.builtin.command: config load --yes

- name: Config reload
  ansible.builtin.command: config reload --yes
  async: 120
  poll: 0
  notify: Wait for new connection

- name: Wait for new connection
  ansible.builtin.wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 30
    timeout: 300

- name: Restart bgp
  ansible.builtin.systemd:
    name: bgp
    state: restarted
