---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: virtual-garden-kubeconfig-refresher
  name: virtual-garden-kubeconfig-refresher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-garden-kubeconfig-refresher
  template:
    metadata:
      labels:
        app: virtual-garden-kubeconfig-refresher
    spec:
      enableServiceLinks: False
      serviceAccountName: virtual-garden-kubeconfig-refresher
      containers:
      - name: refresher
        image: {{ virtual_garden_kubeconfig_refresher_image_name }}:{{ virtual_garden_kubeconfig_refresher_image_tag }}
        imagePullPolicy: {{ metal_control_plane_image_pull_policy }}
        env:
        - name: NAMESPACE
          value: "{{ monitoring_namespace }}"
        - name: TOKEN_FILE_PATH
          value: "/etc/virtual-garden-kubeconfig/token"
        - name: KUBECONFIG_FILE_PATH
          value: "/etc/virtual-garden-kubeconfig/kubeconfig"
{% if monitoring_virtual_garden_kubeconfig_refresher_gcp_enabled %}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /gcp/gcp_service_account.json
        - name: GOOGLE_PROJECT_ID
          value: "{{ monitoring_virtual_garden_kubeconfig_refresher_gcp_project_id }}"
        - name: GOOGLE_LOCATION
          value: "{{ monitoring_virtual_garden_kubeconfig_refresher_gcp_location }}"
        - name: GOOGLE_CLUSTER_NAME
          value: "{{ monitoring_virtual_garden_kubeconfig_refresher_gcp_cluster_name }}"
        volumeMounts:
        - name: gcp
          mountPath: /gcp
          readOnly: true
      volumes:
        - name: gcp
          secret:
            secretName: virtual-garden-kubeconfig-refresher
            items:
              - key: gcp_service_account.json
                path: gcp_service_account.json
{% endif %}
{% if monitoring_virtual_garden_kubeconfig_refresher_metal_stack_cloud_enabled %}
        - name: METAL_STACK_CLOUD_PROJECT_ID
          value: "{{ monitoring_virtual_garden_kubeconfig_refresher_metal_stack_cloud_project_id }}"
        - name: METAL_STACK_CLOUD_API_TOKEN
          value: "{{ monitoring_virtual_garden_kubeconfig_refresher_metal_stack_cloud_api_token }}"
        - name: METAL_STACK_CLOUD_CLUSTER_ID
          value: "{{ monitoring_virtual_garden_kubeconfig_refresher_metal_stack_cloud_cluster_id }}"
{% endif %}
{% if monitoring_virtual_garden_kubeconfig_refresher_garden_cluster_enabled %}
        - name: GARDEN_CLUSTER_KUBECONFIG
          valueFrom:
            secretKeyRef:
              name: virtual-garden-kubeconfig-garden-cluster
              key: GARDEN_CLUSTER_KUBECONFIG
{% endif %}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: virtual-garden-kubeconfig-refresher
  name: virtual-garden-kubeconfig-refresher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: virtual-garden-kubeconfig-refresher
  name: virtual-garden-kubeconfig-refresher
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - update
  - watch
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: virtual-garden-kubeconfig-refresher
  name: virtual-garden-kubeconfig-refresher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: virtual-garden-kubeconfig-refresher
  namespace: {{ monitoring_namespace }}
subjects:
- kind: ServiceAccount
  name: virtual-garden-kubeconfig-refresher
  namespace: {{ monitoring_namespace }}
{% if monitoring_virtual_garden_kubeconfig_refresher_garden_cluster_local_rbac %}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: virtual-garden-kubeconfig-refresher
  name: virtual-garden-kubeconfig-refresher
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resources.gardener.cloud/v1alpha1
  resources:
  - managedresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.gardener.cloud
  resources:
  - gardens
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: virtual-garden-kubeconfig-refresher
  name: virtual-garden-kubeconfig-refresher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: virtual-garden-kubeconfig-refresher
subjects:
- kind: ServiceAccount
  name: virtual-garden-kubeconfig-refresher
  namespace: {{ monitoring_namespace }}
{% endif %}