---
k3s_server_router_id: "{{ k3s_server_loopback_address }}"
k3s_server_peer_group: K3S
k3s_server_bgp_timers: "1 3"
k3s_server_syslog_level: informational

k3s_server_accept_prefixes:
  - 0.0.0.0/0
k3s_server_announce_prefixes:
  - "{{ k3s_server_loopback_address }}/32"

k3s_server_version: v1.36.4+k3s1
k3s_server_install_script_url: https://get.k3s.io
k3s_server_release_url: https://github.com/k3s-io/k3s/releases/download
k3s_server_binary_url: "{{ k3s_server_release_url }}/{{ k3s_server_version | replace('+', '%2B') }}/k3s"
k3s_server_checksum_url: "{{ k3s_server_release_url }}/{{ k3s_server_version | replace('+', '%2B') }}/sha256sum-amd64.txt"
k3s_server_install_script_path: /usr/local/share/k3s-install.sh
k3s_server_config_dir: /etc/rancher/k3s

k3s_server_cluster_init_host:
k3s_server_token:

k3s_server_api_port: 6443
k3s_server_api_timeout: 300
k3s_server_cluster_cidr: 10.42.0.0/16
k3s_server_service_cidr: 10.43.0.0/16

k3s_server_flannel_iface:
k3s_server_flannel_mtu:

k3s_server_tls_sans: []
k3s_server_disable:
  - traefik
  - servicelb
k3s_server_config_extra: {}
