---
- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

- name: Reload frr
  ansible.builtin.service:
    name: frr
    enabled: true
    state: reloaded

- name: Restart frr
  ansible.builtin.service:
    name: frr
    enabled: true
    state: restarted

- name: Reload docker
  ansible.builtin.service:
    name: docker
    enabled: true
    state: reloaded

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Save iptables v4 rules
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
  listen: persist iptables

- name: Save iptables v6 rules
  ansible.builtin.shell: ip6tables-save > /etc/iptables/rules.v6
  listen: persist iptables

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    enabled: true
    state: restarted
