---
- name: Gather switch facts
  switch_facts:

- name: Check mandatory variables for this role are set
  ansible.builtin.assert:
    fail_msg: "not all mandatory variables given, check role documentation"
    quiet: true
    that:
      - dhcp_listening_interfaces | type_debug == "list"
      - item.network is defined
      - item.netmask is not none
      - item.range is not none
      - item.range.begin is not none
      - item.range.end is not none
  loop: "{{ dhcp_subnets }}"
  loop_control:
    label: "{{ item.network }}"

- name: Ensure config directories are present
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /etc/dhcp
    - /etc/default

- name: Render dhcpd conf
  ansible.builtin.template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  register: _dhcpd_conf

- name: Render isc-dhcp-server config
  ansible.builtin.template:
    src: isc-dhcp-server.j2
    dest: /etc/default/isc-dhcp-server
  register: _isc_dhcp_server

- name: Render static hosts config
  ansible.builtin.template:
    src: dhcpd.hosts.j2
    dest: /etc/dhcp/dhcpd.hosts
  when: dhcp_static_hosts is defined
  register: _hosts_conf

- name: Install isc-dhcp-server
  ansible.builtin.apt:
    name:
      - isc-dhcp-server
    update_cache: true

# we want this task to be run at this point and not at the end of the playbook
# this is why we don't use a handler here
- name: Restart isc-dhcp-server on config change
  ansible.builtin.service:
    name: "{{ dhcp_service_name }}"
    enabled: true
    state: restarted
    daemon-reload: true
  when: _dhcpd_conf is changed or _isc_dhcp_server is changed or _hosts_conf is changed

- name: Ensure isc-dhcp-server is running
  ansible.builtin.service:
    name: "{{ dhcp_service_name }}"
    enabled: true
    state: started
