---
gardener_operator_garden_name: "{{ gardener_defaults_garden_name }}"

gardener_operator_repo_url: "{{ gardener_repo_url }}"
gardener_operator_repo_ref: "{{ gardener_repo_ref }}"

gardener_operator_runtime_cluster_provider: local

gardener_operator_backup_infrastructure:
  # provider: gcp
  # region:
  # secretRef:
  #  name: backup-secret
  #  namespace: garden
  # bucket:
  #
  # provider: S3
  # endpoint: "{{ gardener_operator_backup_infrastructure_secret.endpoint | b64decode }}"
  # accessKeyID: "{{ gardener_operator_backup_infrastructure_secret.accessKeyID | b64decode }}"
  # secretAccessKey: "{{ gardener_operator_backup_infrastructure_secret.secretAccessKey | b64decode}}"

gardener_operator_backup_infrastructure_secret:
  # for gcp:
  # serviceaccount.json: "{{ gardener_operator_backup_infrastructure_service_account_json | b64encode }}"
  #
  # for S3:
  # endpoint:
  # accessKeyID:
  # secretAccessKey:

gardener_operator_dns_providers: []
  # - name: powerdns
  #   type: powerdns
  #   secretData:

gardener_operator_high_availability_control_plane: true

gardener_operator_image_vector_overwrite:
gardener_operator_component_image_vector_overwrite:
  # components:
  # - name: etcd-druid
  #   imageVectorOverwrite: |
  #     images:
  #     - name: etcd-backup-restore
  #       sourceRepository: github.com/gardener/etcd-backup-restore
  #       repository: europe-docker.pkg.dev/gardener-project/public/gardener/etcdbrctl
  #       tag: "v0.36.3"

gardener_operator_helm_chart_tag: "{{ gardener_operator_image_tag }}"

gardener_operator_shoot_admin_kubeconfig_max_expiration: "24h"

gardener_operator_dashboard_enabled: false
gardener_operator_dashboard_oidc_session_lifetime: 12h
gardener_operator_dashboard_oidc_additional_scopes: [ profile, offline_access ]
gardener_operator_dashboard_oidc_client_id:
gardener_operator_dashboard_oidc_client_secret:
gardener_operator_dashboard_log_level: debug
gardener_operator_dashboard_ingress_enabled: true
gardener_operator_wildcard_ingress_certificate_cluster_issuer:

gardener_operator_dashboard_config_frontend:
  # landingPageUrl:
  # branding:
  # themes:
  # colors:

gardener_operator_dashboard_config_assets:
  # favicon_16:
  # favicon_32:
  # favicon_96:
  # favicon_ico:
  # logo_svg: