---
galaxy_info:
  role_name: vector-goflow2
  author: metal-stack
  description: Deploys Vector enrichment tables and configuration for the goflow2 sFlow pipeline.
  license: MIT
  min_ansible_version: "2.10"
  galaxy_tags: []

  platforms:
    - name: GenericLinux
      versions:
        - all

dependencies:
  - role: metal-roles/common/roles/defaults
  - role: metal-roles/control-plane/roles/defaults
