---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: extension-shoot-dns-service
type: helm
providerConfig:
  chart: "{{ (lookup('url', 'https://raw.githubusercontent.com/gardener/gardener-extension-shoot-dns-service/v1.46.0/example/controller-registration.yaml', split_lines=False) | from_yaml_all | list)[0].providerConfig.chart }}"
  values:
    image:
      repository: "{{ gardener_shoot_dns_service_image_name }}"
      tag: "{{ gardener_shoot_dns_service_image_tag }}"
{% if gardener_shoot_dns_service_image_vector_overwrite %}
    imageVectorOverwrite:
      images:
        {{ gardener_shoot_dns_service_image_vector_overwrite | to_nice_yaml(indent=2) | indent(width=8, first=false) }}
  {% endif %}
    dnsProviderManagement:
      enabled: true
    dnsControllerManager:
      deploy: true
