---
galaxy_info:
  role_name: sonic
  author: metal-stack
  description: "DEPRECATED: Deploys a SONiC switch."
  license: MIT
  min_ansible_version: "2.10"
  galaxy_tags: []
  platforms:
    - name: Debian
      versions:
        - all

dependencies:
  - role: ansible-common
