---
# https://archive.grafana.com/docs/loki/v2.8.x/installation/helm/reference/
# https://archive.grafana.com/docs/loki/v2.8.x/installation/helm/install-monolithic/
singleBinary:
  replicas: 1
  persistence:
    size: {{ logging_loki_size }}
{% if logging_loki_storage_class %}
    storageClass: {{ logging_loki_storage_class }}
{% endif %}

loki:
  auth_enabled: false

  # See README.md "Persistent storage" for the rationale behind these settings.
  commonConfig:
    # path_prefix: /var/loki
    replication_factor: 1
    ring:
      instance_addr: 127.0.0.1
      kvstore:
        store: inmemory
  storage:
    type: 'filesystem'

  ingester:
    chunk_idle_period: 1h
    chunk_retain_period: 30s

  limits_config:
    ingestion_rate_mb: 32
    ingestion_burst_size_mb: 64
    per_stream_rate_limit: "16MB"
    per_stream_rate_limit_burst: "32MB"
{% if logging_loki_retention_enabled %}
    retention_period: {{ logging_loki_retention_period }}
    deletion_mode: {{ logging_loki_deletion_mode }}
{% if logging_loki_retention_stream %}
    retention_stream:
{{ logging_loki_retention_stream | to_yaml | indent(6, first=true) }}
{% endif %}
{% endif %}

  compactor:
    shared_store: filesystem
    retention_enabled: {{ logging_loki_retention_enabled | lower }}

gateway:
  enabled: false

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
{% for key, value in logging_ingress_annotations.items() %}
    {{ key }}: "{{ value }}"
{% endfor %}
{% if logging_ingress_loki_basic_auth_user and logging_ingress_loki_basic_auth_password %}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: loki-basic-auth
{% endif %}
  hosts:
    - {{ logging_ingress_dns }}
{% if logging_ingress_loki_tls %}
  tls:
    - hosts:
      - {{ logging_ingress_dns }}
      secretName: monitoring-loki-ingress-tls
{% endif %}

{% if logging_ingress_loki_basic_auth_user and logging_ingress_loki_basic_auth_password %}
extraObjects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: loki-basic-auth
  type: Opaque
  stringData:
    auth: "{{ logging_ingress_loki_basic_auth_user }}:{{ logging_ingress_loki_basic_auth_password | string | password_hash('bcrypt', salt=logging_ingress_loki_basic_auth_password_salt) }}"
{% endif %}
