---
gardener_partition_proxy_garden_name: "{{ gardener_defaults_garden_name }}"

gardener_partition_proxy_metal_api_url:
gardener_partition_proxy_metal_api_edit_hmac:

gardener_partition_proxy_dns_credentials:
gardener_partition_proxy_dns_provider:

gardener_partition_proxy_ip_address:

# TODO: move to release vector?
gardener_partition_proxy_image_name: nginx
gardener_partition_proxy_image_tag: 1.29-alpine

gardener_partition_proxy_shooted_seeds: []
  # - name: seed-a
  #   metal_project_id:
  #   metal_network_id:
  #   proxy_servers:
  #     - name: duros
  #       ingress_domain: duros.fra-equ01.proxy.metal-stack.dev
  #       mtls: true           # optional, defaults to true
  #       ca:
  #       cert:
  #       cert_key:
  #       addresses:
  #         - <address>:443
  #       type: grpcs
  #     - name: ontap
  #       ingress_domain: ontap.fra-equ01.proxy.metal-stack.dev
  #       mtls: false
  #       cert:
  #       cert_key:
  #       addresses:
  #         - <address>:443
  #       type: https
