---
sflow_collector_port: 6343
sflow_collector_metrics_port: 9099
sflow_collector_internal_port: 9001

sflow_collector_image_name: netsampler/goflow2
sflow_collector_image_tag: latest

sflow_collector_vector_image_name: timberio/vector
sflow_collector_vector_image_tag: 0.55.0-distroless-libc

sflow_collector_vector_geo_sample_rate: 10

sflow_collector_config_host_dir: /etc/sflow-collector
sflow_collector_data_host_dir: /var/lib/sflow-collector

sflow_collector_loki_endpoint:
sflow_collector_loki_basic_auth_user:
sflow_collector_loki_basic_auth_password:
sflow_collector_loki_tls_verify: true

sflow_collector_geoip_download_image: alpine:3

sflow_collector_docker_log_driver: json-file

sflow_collector_spool_tmpfs_size: 256m

sflow_collector_logrotate_size: 32M
sflow_collector_logrotate_keep: 1
sflow_collector_logrotate_interval: 2min

sflow_collector_vector_buffer_max_events: 100000
