---
- name: Gather switch facts
  switch_facts:

- name: Check mandatory variables for this role are set
  ansible.builtin.assert:
    fail_msg: "not all mandatory variables given, check role documentation"
    quiet: true
    that:
      - sonic_mgmt_vrf is defined
      - sonic_loopback_address is defined
      - sonic_asn is defined
      - sonic_config_action in ['load', 'reload']
      - sonic_ntpservers is defined
      - sonic_nameservers is defined
      - metal_stack_switch_os_is_sonic

- name: Render resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: "0644"

- name: Activate IP MASQUERADE on eth0
  ansible.builtin.iptables:
    chain: POSTROUTING
    jump: MASQUERADE
    out_interface: eth0
    table: nat
  when: sonic_ip_masquerade

- name: Activate ipv4 forwarding on eth0
  ansible.posix.sysctl:
    name: net.ipv4.conf.eth0.forwarding
    reload: false
    sysctl_set: true
    value: "1"
  when: sonic_ip_masquerade

- name: Render and save config_db
  ansible.builtin.import_tasks: config_db.yaml
  when: sonic_render_config_db_template

- name: Set NTP timezone
  community.general.timezone:
    name: "{{ sonic_timezone }}"

- name: Render frr config
  ansible.builtin.template:
    src: frr.conf.j2
    dest: /etc/sonic/frr/frr.conf
    mode: "0644"
  when: sonic_frr_render
  notify:
    - Restart bgp

- name: Render iptables.json
  ansible.builtin.template:
    src: iptables.json.j2
    dest: /etc/sonic/iptables.json
    mode: "0644"
  when: sonic_extended_cacl is defined
  notify:
    - Restart caclmgrd

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
