---
- name: Ensure gpg is installed to handle FRR repo key
  ansible.builtin.apt:
    name:
      - gpg
    update_cache: true
    force_apt_get: true

- name: Download GPG key
  ansible.builtin.get_url:
    url: https://deb.frrouting.org/frr/keys.gpg
    dest: /usr/share/keyrings/frrouting.gpg
    mode: "0644"

- name: Add mainline FRR repository to install FRR
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/frrouting.gpg] https://deb.frrouting.org/frr {{ ansible_distribution_release }} {{ mgmt_server_frr_repo }}
    state: present
    filename: frr.list

- name: Install required packages to have the network stack in place
  ansible.builtin.apt:
    name:
      - frr={{ mgmt_server_frr_version }}*
      - frr-pythontools={{ mgmt_server_frr_version }}*
    update_cache: true
    force_apt_get: true

- name: Enable bgp daemons required to run bgp
  ansible.builtin.copy:
    src: daemons
    dest: /etc/frr/daemons
    mode: "0640"
  notify: Restart frr
