---
apiVersion: v1
kind: ConfigMap
metadata:
  name: partition-proxy
  namespace: partition-proxy
data:
  haproxy.cfg: |
    {{ lookup('template', 'haproxy.cfg') | indent(width=4, first=false) }}
  crt-list.cfg: |
    {{ lookup('template', 'crt-list.cfg') | indent(width=4, first=false) }}
{% for conf in gardener_shooted_seed.proxy_servers %}
---
apiVersion: v1
kind: Secret
metadata:
  name: partition-proxy-{{ conf.name }}
  namespace: partition-proxy
type: Opaque
data:
{% if conf.mtls | default(true) %}
  ca.pem: "{{ conf.ca | b64encode }}"
{% endif %}
  combined.pem: "{{ (conf.cert ~ '\n' ~ conf.cert_key) | b64encode }}"
{% endfor %}
