{{ lookup('template', 'configs.yaml') }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: partition-proxy
  namespace: partition-proxy
  labels:
    app.kubernetes.io/name: "partition-proxy"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "partition-proxy"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "partition-proxy"
        config-hash: "{{ lookup('template', 'configs.yaml') | hash('sha1') }}"
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: proxy
          image: "{{ gardener_partition_proxy_image_name }}:{{ gardener_partition_proxy_image_tag }}"
          ports:
            - containerPort: 443
            - containerPort: 8404
          livenessProbe:
            httpGet:
              path: /
              port: 8404
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8404
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: haproxy-conf
              mountPath: /usr/local/etc/haproxy
              readOnly: true
{% for conf in gardener_shooted_seed.proxy_servers %}
            - name: certs-{{ conf.name }}
              mountPath: /etc/ssl/{{ conf.name }}
              readOnly: true
{% endfor %}
      volumes:
        - name: haproxy-conf
          configMap:
            name: partition-proxy
{% for conf in gardener_shooted_seed.proxy_servers %}
        - name: certs-{{ conf.name }}
          secret:
            secretName: partition-proxy-{{ conf.name }}
{% endfor %}
---
apiVersion: v1
kind: Service
metadata:
  name: partition-proxy
  namespace: partition-proxy
  labels:
    app.kubernetes.io/name: "partition-proxy"
spec:
  type: LoadBalancer
  loadBalancerIP: "{{ _proxy_ip }}"
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: "partition-proxy"
