---
galaxy_info:
  role_name: k3s-server
  author: metal-stack
  description: Configures a k3s server of the autonomous control plane and the BGP sessions to the leaves it is attached to.
  license: MIT
  min_ansible_version: "2.10"
  galaxy_tags: []
  platforms:
    - name: Debian
      versions:
        - all

dependencies: []
