---
galaxy_info:
  role_name: promtail
  author: metal-stack
  description: "DEPRECATED: Deploys promtail. Use metal-roles/partition/roles/alloy instead."
  license: MIT
  min_ansible_version: "2.10"
  galaxy_tags: []

  platforms:
    - name: Debian
      versions:
        - all

dependencies:
  - role: metal-roles/common/roles/defaults
  - role: metal-roles/partition/roles/defaults
