---
- name: Gather release versions
  setup_yaml:

- name: Create prometheus directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "nobody"
    group: "nogroup"
    mode: "0755"
  loop:
    - "{{ prometheus_config_host_dir }}"
    - "{{ prometheus_config_host_dir }}/file_sd"
    - "{{ prometheus_data_host_dir }}"

- name: Generate /etc/hosts
  ansible.builtin.copy:
    content: "{{ prometheus_hosts_content }}"
    dest: "{{ prometheus_config_host_dir }}/hosts"
    mode: "0644"
  when: prometheus_hosts_content

- name: Generate prometheus.yaml
  ansible.builtin.template:
    src: prometheus.yaml.j2
    dest: "{{ prometheus_config_host_dir }}/prometheus.yaml"
    mode: "0644"
  notify: Restart prometheus

- name: Generate prometheus_metal_core_sd
  ansible.builtin.set_fact:
    prometheus_metal_core_sd:
      - labels:
          job: metal-core
        targets: "{{ prometheus_metal_core_targets }}"

- name: Create metal-core.yaml
  ansible.builtin.copy:
    content: "{{ prometheus_metal_core_sd | to_nice_yaml(indent=2) }}"
    dest: "{{ prometheus_config_host_dir }}/file_sd/metal-core.yaml"
    mode: "0644"
  notify: Restart prometheus

- name: Generate prometheus_node_exporter_sd
  ansible.builtin.set_fact:
    prometheus_node_exporter_sd:
      - labels:
          job: node-exporter
        targets: "{{ prometheus_node_exporter_targets }}"

- name: Create node-exporter.yaml
  ansible.builtin.copy:
    content: "{{ prometheus_node_exporter_sd | to_nice_yaml(indent=2) }}"
    dest: "{{ prometheus_config_host_dir }}/file_sd/node-exporter.yaml"
    mode: "0644"
  notify: Restart prometheus

- name: Generate prometheus_frr_exporter_sd
  ansible.builtin.set_fact:
    prometheus_frr_exporter_sd:
      - labels:
          job: frr
        targets: "{{ prometheus_frr_exporter_targets }}"

- name: Create frr-exporter.yaml
  ansible.builtin.copy:
    content: "{{ prometheus_frr_exporter_sd | to_nice_yaml(indent=2) }}"
    dest: "{{ prometheus_config_host_dir }}/file_sd/frr-exporter.yaml"
    mode: "0644"
  notify: Restart prometheus

- name: Create static ipmi-exporter targets file
  ansible.builtin.copy:
    content: |
      ---
      - labels:
          job: ipmi
        targets: {{ prometheus_ipmi_exporter_targets | to_json }}
    dest: "{{ prometheus_config_host_dir }}/file_sd/ipmi.yaml"
    mode: "0644"
  notify: Restart prometheus
  when: prometheus_ipmi_exporter_targets

- name: Write systemd timer to dynamically write ipmi-exporter-targets file
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('a=r') }}"
    mode: "0644"
  loop:
    - template: ipmi-exporter-targets.service.j2
      dest: /etc/systemd/system/ipmi-exporter-targets.service
    - template: ipmi-exporter-targets.timer.j2
      dest: /etc/systemd/system/ipmi-exporter-targets.timer
    - template: ipmi-exporter-targets.py
      dest: "{{ prometheus_config_host_dir }}/ipmi-exporter-targets.py"
      mode: "a+x"
  loop_control:
    label: "{{ item.dest }}"
  when: not prometheus_ipmi_exporter_targets

- name: Enable ipmi-exporter-targets
  ansible.builtin.systemd:
    name: ipmi-exporter-targets.{{ item }}
    daemon_reload: true
    enabled: true
    state: started
  loop:
    - service
    - timer
  when: not prometheus_ipmi_exporter_targets

- name: Disable ipmi-exporter-targets
  ansible.builtin.systemd:
    name: ipmi-exporter-targets.{{ item }}
    enabled: false
    state: stopped
  failed_when: '_result is failed and ("msg" in _result and "Could not find the requested service" not in _result.msg)'
  loop:
    - service
    - timer
  register: _result
  when: prometheus_ipmi_exporter_targets

- name: Generate prometheus_promtail_sd
  ansible.builtin.set_fact:
    prometheus_promtail_sd:
      - labels:
          job: promtail
        targets: "{{ prometheus_promtail_targets }}"

- name: Create promtail.yaml
  ansible.builtin.copy:
    content: "{{ prometheus_promtail_sd | to_nice_yaml(indent=2) }}"
    dest: "{{ prometheus_config_host_dir }}/file_sd/promtail.yaml"
    mode: "0644"
  notify: Restart prometheus

- name: Generate prometheus_alloy_sd
  ansible.builtin.set_fact:
    prometheus_alloy_sd:
      - labels:
          job: alloy
        targets: "{{ prometheus_alloy_targets }}"

- name: Create alloy.yaml
  ansible.builtin.copy:
    content: "{{ prometheus_alloy_sd | to_nice_yaml(indent=2) }}"
    dest: "{{ prometheus_config_host_dir }}/file_sd/alloy.yaml"
    mode: "0644"
  notify: Restart prometheus

- name: Generate prometheus_sonic_exporter_sd
  ansible.builtin.set_fact:
    prometheus_sonic_exporter_sd:
      - labels:
          job: sonic-exporter
        targets: "{{ prometheus_sonic_exporter_targets }}"

- name: Create sonic-exporter.yaml
  ansible.builtin.copy:
    content: "{{ prometheus_sonic_exporter_sd | to_nice_yaml(indent=2) }}"
    dest: "{{ prometheus_config_host_dir }}/file_sd/sonic-exporter.yaml"
    mode: "0644"
  notify: Restart prometheus

- name: Generate prometheus_blackbox_exporter_sd
  ansible.builtin.set_fact:
    prometheus_blackbox_exporter_sd:
      - labels:
          job: blackbox-exporter
        targets: "{{ prometheus_blackbox_exporter_targets }}"

- name: Create blackbox-exporter.yaml
  ansible.builtin.copy:
    content: "{{ prometheus_blackbox_exporter_sd | to_nice_yaml(indent=2) }}"
    dest: "{{ prometheus_config_host_dir }}/file_sd/blackbox-exporter.yaml"
    mode: "0644"
  notify: Restart prometheus

- name: Ensure rules directory
  ansible.builtin.file:
    path: "{{ prometheus_config_host_dir }}/rules"
    state: directory
    mode: "0644"

- name: Copy notification rules
  ansible.builtin.copy:
    content: |
      groups:
      {{ lookup('ansible.builtin.vars', item.content_var) | indent(width=4) }}
    dest: "{{ prometheus_config_host_dir }}/rules/{{ item.file }}"
    mode: "0644"
  loop:
    - file: blackbox-exporter.yaml
      content_var: partition_prometheus_rules_blackbox_exporter
    - file: haproxy.yaml
      content_var: partition_prometheus_rules_haproxy
    - file: ipmi-rules.yaml
      content_var: partition_prometheus_rules_ipmi
    - file: leaf-rules.yaml
      content_var: partition_prometheus_rules_leaf
    - file: node-exporter.yaml
      content_var: partition_prometheus_rules_node_exporter
    - file: pixiecore-rules.yaml
      content_var: partition_prometheus_rules_pixiecore
    - file: sonic-exporter.yaml
      content_var: partition_prometheus_rules_sonic_exporter
  notify: Restart prometheus

- name: Deploy prometheus service
  ansible.builtin.include_role:
    name: ansible-common/roles/systemd-docker-service
  vars:
    systemd_service_name: prometheus
    systemd_docker_image_name: "{{ prometheus_image_name }}"
    systemd_docker_image_tag: "{{ prometheus_image_tag }}"
    systemd_service_after: docker.service
    systemd_service_requires: docker.service
    systemd_docker_network: host
    systemd_docker_volumes: "{{ lookup('template', 'prometheus-volumes.yaml.j2') | from_yaml }}"
    systemd_docker_command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-lifecycle
      - --storage.tsdb.retention.time=6h
      - --storage.tsdb.no-lockfile
      - --storage.tsdb.min-block-duration=2h
      - --storage.tsdb.max-block-duration=2h
    systemd_docker_log_driver: "{{ prometheus_docker_log_driver }}"

- name: Wait for prometheus to listen on port
  ansible.builtin.wait_for:
    port: "{{ prometheus_port }}"
    timeout: 300
    msg: "prometheus did not come up"
