---
- name: Check mandatory variables for this role are set
  assert:
    fail_msg: "not all mandatory variables given, check role documentation"
    quiet: yes
    that:
      - sflow_collector_namespace is defined

- name: Deploy goflow2
  k8s:
    state: present
    definition: "{{ lookup('template', 'deployment.yaml.j2') | from_yaml_all }}"
