---
- name: Check mandatory variables for this role are set
  ansible.builtin.assert:
    fail_msg: "not all mandatory variables given, check role documentation"
    quiet: true
    that:
      - frr_version is not none
      - frr_repo is not none
      - ansible_os_family in ['Debian', 'RedHat']

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Check if frr is installed
  ansible.builtin.set_fact:
    frr_installed: "{{ ('packages' in ansible_facts and ('frr' in ansible_facts.packages) and (frr_version | string in (ansible_facts.packages['frr'][0].version)))
      | bool }}"

- name: Import tasks for Debian
  ansible.builtin.import_tasks: install/debian.yaml
  when: not frr_installed and ansible_os_family == 'Debian'

- name: Import tasks for RedHat
  ansible.builtin.import_tasks: install/redhat.yaml
  when: not frr_installed and ansible_os_family == 'RedHat'

- name: Copy sysctls for frr
  ansible.builtin.copy:
    src: sysctl.conf
    dest: /etc/sysctl.d/98-frr.conf
    mode: "0644"
  notify: Reload sysctls

- name: Enable vtysh
  ansible.builtin.copy:
    src: vtysh.conf
    dest: /etc/frr/
    mode: "0640"
  notify: Restart frr

- name: Enable frr daemons
  ansible.builtin.copy:
    src: daemons
    dest: /etc/frr/daemons
    mode: "0640"
  notify: Restart frr

- name: Ensure frr is started
  ansible.builtin.systemd:
    name: frr
    enabled: true
    state: started

- name: Copy frr conf
  ansible.builtin.copy:
    content: "{{ frr_conf }}"
    dest: /etc/frr/frr.conf
    mode: "0640"
  notify: Reload frr
