---
- name: Create backup infrastructure secret
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: virtual-garden-etcd-main-backup-secret
        namespace: garden
      type: Opaque
      data: "{{ gardener_operator_backup_infrastructure_secret }}"
    apply: yes
  no_log: yes

- name: Create DNS provider secrets
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: virtual-garden-dns-provider-{{ provider.name | lower }}-secret
        namespace: garden
      type: Opaque
      data: "{{ provider.secretData }}"
    apply: yes
  loop: "{{ gardener_operator_dns_providers }}"
  loop_control:
    loop_var: provider
    label: "{{ provider.name }}"
  no_log: yes

- name: Create kube-apiserver authentication configmap
  k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: authentication-config
        namespace: garden
      data:
        config.yaml: |-
          {{ gardener_operator_virtual_garden_api_server_structured_authentication }}
    apply: yes
  when: gardener_operator_virtual_garden_api_server_structured_authentication
  no_log: yes

- name: Create gardener dashboard oidc secret
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gardener-dashboard-oidc
        namespace: garden
      type: Opaque
      stringData:
        client_id: "{{ gardener_operator_dashboard_oidc_client_id | string }}"
        client_secret: "{{ gardener_operator_dashboard_oidc_client_secret | string }}"
    apply: yes
  when: gardener_operator_dashboard_enabled
  no_log: yes

- name: Create gardener dashboard frontend configmap
  k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: gardener-dashboard-frontend
        namespace: garden
      data:
        frontend-config.yaml: |-
          {{ gardener_operator_dashboard_frontend_config }}
    apply: yes
  when:
    - gardener_operator_dashboard_enabled
    - gardener_operator_dashboard_frontend_config

# - name: Create gardener dashboard assets configmap
#   k8s:
#     definition:
#       apiVersion: v1
#       kind: ConfigMap
#       metadata:
#         name: gardener-dashboard-assets
#         namespace: garden
#       binaryData:
#         favicon-16x16.png: base64(favicon-16x16.png)
#         favicon-32x32.png: base64(favicon-32x32.png)
#         favicon-96x96.png: base64(favicon-96x96.png)
#         favicon.ico: base64(favicon.ico)
#         logo.svg: base64(logo.svg)
#     apply: yes
#   when: gardener_operator_dashboard_enabled
#   no_log: yes

- name: Deploy Gardener Operator
  include_role:
    name: ansible-common/roles/helm-chart
  vars:
    helm_timeout: "600s"
    helm_chart: "oci://{{ gardener_operator_helm_chart }}"
    helm_chart_version: "{{ gardener_operator_helm_chart_tag }}"
    helm_release_name: operator
    helm_target_namespace: garden
    helm_value_file_template: gardener-operator-values.j2

- name: Create Garden
  k8s:
    definition: "{{ lookup('template', 'garden.yaml') }}"
    apply: yes
