---
- name: Gather release versions
  setup_yaml:

- name: Check mandatory variables are set
  ansible.builtin.assert:
    quiet: true
    that:
      - sonic_config_loopback_address

- name: Check mandatory variables for frr.conf are set
  ansible.builtin.assert:
    quiet: true
    that:
      - sonic_config_asn is defined
  when: sonic_config_frr_render

- name: Render resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: Generate config_db.json
  ansible.builtin.import_tasks: generate_config_db.yaml
- name: Set NTP timezone
  community.general.timezone:
    name: "{{ sonic_config_timezone }}"

- name: Render frr config
  ansible.builtin.template:
    src: frr.conf.j2
    dest: /etc/sonic/frr/frr.conf
  when: sonic_config_frr_render
  notify:
    - Reload frr

- name: Render iptables.json
  ansible.builtin.template:
    src: iptables.json.j2
    dest: /etc/sonic/iptables.json
  when: sonic_config_extended_cacl is defined
  notify:
    - Restart caclmgrd

- name: Install frr-reload.service
  ansible.builtin.copy:
    src: frr-reload.service
    dest: /etc/systemd/system/frr-reload.service

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
