apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: auditing-timescaledb
spec:
  selector:
    matchLabels:
      app: auditing-timescaledb
  namespaceSelector:
    matchNames:
    - {{ metal_control_plane_namespace }}
  endpoints:
  - port: "metrics"
    interval: 60s
