---
- name: Set admin api token for deployment
  delegate_to: localhost
  run_once: true
  when: metal_deployment_admin_token is not defined
  block:
    - name: Read metal-apiserver token secret
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: "{{ metal_deployment_token_secret_name }}"
        namespace: "{{ metal_deployment_token_secret_namespace }}"
      register: _token_secret

    - name: Set deployment token
      ansible.builtin.set_fact:
        metal_deployment_admin_token: "{{ _token_secret.resources[0].data[metal_deployment_token_secret_key] | b64decode }}"
