---
- name: Restart caclmgrd
  ansible.builtin.systemd:
    name: caclmgrd
    state: restarted

- name: Reload frr
  ansible.builtin.systemd:
    name: frr-reload.service
    state: restarted
  retries: 2
