---
gardener_virtual_garden_access_garden_name: "{{ gardener_defaults_garden_name }}"
gardener_virtual_garden_access_expiration: 8h
gardener_virtual_garden_access_cluster_role_bindings: []
  # - apiVersion: rbac.authorization.k8s.io/v1
  #   kind: ClusterRoleBinding
  #   metadata:
  #     name: platform-admins
  #   roleRef:
  #     apiGroup: rbac.authorization.k8s.io
  #     kind: ClusterRole
  #     name: cluster-admin
  #   subjects:
  #   - apiGroup: rbac.authorization.k8s.io
  #     kind: User
  #     name: oidc:admin@metal-stack.auth.metal-stack.dev
