---
- name: Create metal-apiserver token for metal-image-cache-sync
  ansible.builtin.import_role:
    name: metal-roles/common/roles/metal-deployment-token

- name: Check metal-deployment-token has run
  ansible.builtin.assert:
    fail_msg:
      "this role requires the metal-deployment-token role to be run before
      execution, check role documentation"
    quiet: true
    that:
      - "'metal_deployment_admin_token' in hostvars['localhost']"

- name: Create api tokens for metal-image-cache-sync
  delegate_to: localhost
  environment:
    METALCTLV2_API_URL: "{{ image_cache_sync_metal_apiserver_url }}"
    METALCTLV2_API_TOKEN: "{{ hostvars['localhost'].metal_deployment_admin_token }}"
  block:
    - name: Create image-cache tenant
      metal_v2_admin_tenant:
        identifier: image-cache
        name: metal-image-cache-sync-{{ metal_partition_id }}-{{ inventory_hostname }}
        description: tenant used by the metal-image-cache-sync service in the metal-stack partitions
      register: _tenant

    - name: Create image-cache api token
      metal_v2_admin_token:
        identifier: image-cache
        user: "{{ _tenant.id }}"
        description: "metal-image-cache-sync token {{ inventory_hostname }} in partition {{ metal_partition_id }}"
        expires: "{{ image_cache_sync_token_expiration }}"
        permissions:
          - subject: ""
            methods:
              - /metalstack.api.v2.ImageService/List
              - /metalstack.api.v2.TokenService/Refresh
              - /metalstack.api.v2.PartitionService/List
              - /metalstack.infra.v2.ComponentService/Ping
      register: _token
