---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metal-token-renewal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metal-token-renewal
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["metal-metrics-exporter-config"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metal-token-renewal
subjects:
- kind: ServiceAccount
  name: metal-token-renewal
roleRef:
  kind: Role
  name: metal-token-renewal
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: metal-metrics-exporter-token-refresher
spec:
  schedule: "@hourly"
  jobTemplate:
    metadata:
      name: metal-metrics-exporter-token-refresher
    spec:
      template:
        spec:
          serviceAccountName: metal-token-refresher
          restartPolicy: OnFailure
          containers:
          - name: token-refresher
            image: ghcr.io/metal-stack/metal-token-refresher
            env:
            - name: METAL_APISERVER_URL
              value: {{ monitoring_metal_apiserver_url }}
            - name: TOKEN_SECRET_NAMESPACE
              value: "monitoring"
            - name: TOKEN_SECRET_NAME
              value: "metal-metrics-exporter-config"
            - name: TOKEN_SECRET_KEY
              value: "token"
---
apiVersion: v1
kind: Secret
metadata:
  name: metal-metrics-exporter-config
type: Opaque
stringData:
  url: {{ monitoring_metal_apiserver_url }}
  token: {{ _metal_metrics_exporter_token.secret }}
---
apiVersion: v1
kind: Service
metadata:
  name: metal-metrics-exporter
  labels:
    app: metal-metrics-exporter
spec:
  ports:
    - name: metrics
      port: 9080
      targetPort: metrics
  selector:
    app: metal-metrics-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metal-metrics-exporter
  labels:
    app: metal-metrics-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metal-metrics-exporter
  template:
    metadata:
      labels:
        app: metal-metrics-exporter
    spec:
      automountServiceAccountToken: false
      containers:
        - name: metal-metrics-exporter
          command:
            - /metal-metrics-exporter
          image: {{ monitoring_metal_metrics_exporter_image_name }}:{{ monitoring_metal_metrics_exporter_image_tag }}
          imagePullPolicy: {{ metal_control_plane_image_pull_policy }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 999
          ports:
            - containerPort: 9080
              name: metrics
          env:
            - name: METAL_API_URL
              valueFrom:
                secretKeyRef:
                  name: metal-metrics-exporter-config
                  key: url
            - name: METAL_API_TOKEN_FILE
              value: /var/run/secrets/metal-metrics-exporter-config/token
          volumeMounts:
          - mountPath: /var/run/secrets/metal-metrics-exporter-config
            name: metal-metrics-exporter-config
      volumes:
      - name: metal-metrics-exporter-config
        secret:
          defaultMode: 420
          secretName: metal-metrics-exporter-config
