---
- name: reload frr
  ansible.builtin.service:
    name: frr
    state: reloaded

- name: restart frr
  ansible.builtin.service:
    name: frr
    state: restarted

- name: reload sysctls
  ansible.builtin.command: sysctl --system
