---
- name: Reload frr
  ansible.builtin.service:
    name: frr
    state: reloaded

- name: Restart frr
  ansible.builtin.service:
    name: frr
    state: restarted

- name: Reload sysctls
  ansible.builtin.command: sysctl --system

- name: Restart frr with reloaded systemd units
  ansible.builtin.systemd:
    name: frr
    daemon_reload: true
    state: restarted
