---
# called with loop_var cluster

- name: Install nginx-ingress
  ansible.builtin.import_tasks: ingress.yaml
  when: isolated_clusters_ingress_controller_enabled | bool

- name: Install ntp
  ansible.builtin.import_tasks: ntp.yaml
- name: Install dns
  ansible.builtin.import_tasks: dns.yaml
- name: Install deployment
  ansible.builtin.import_tasks: registry.yaml
- name: Install envoy-gateway
  ansible.builtin.import_tasks: envoy-gateway.yaml
  when: isolated_clusters_envoy_gateway_enabled | bool
