name: Publish OCI Artifact

on:
  pull_request:
    branches:
      - master
  release:
    types:
      - published
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  draft:
    uses: metal-stack/actions-common/.github/workflows/release-drafter.yaml@999a2bd0d754d7b71cd4d4359d20473e78862a4b # v1.0.6

  oci-ansible-role:
    uses: metal-stack/actions-common/.github/workflows/oci-release-vector-artifact.yaml@999a2bd0d754d7b71cd4d4359d20473e78862a4b # v1.0.6
    secrets: inherit
    with:
      artifact-type: ansible-role
