---
- name: Create volumegroup
  community.general.lvg:
    vg: "{{ lvm_vg }}"
    pvs: "{{ lvm_pvs }}"

- name: Create logical volumes
  ansible.builtin.include_tasks: lv.yaml
  loop: "{{ lvm_lvs }}"
  loop_control:
    loop_var: lv
